name: hastlehub
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  cloud_firestore: ^5.4.2
  country_picker: ^2.0.26
  firebase_auth: ^5.3.0
  firebase_core: ^3.5.0
  firebase_storage: ^12.3.2
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  image_picker: ^1.1.2
  windows_taskbar: ^1.1.2
  intl:
  file_picker: ^8.1.3
  geocoding: ^3.0.0
  google_maps_flutter: ^2.9.0
  geolocator: ^13.0.1
  google_place: ^0.4.7
  sqflite: ^2.4.1
  path: ^1.9.0
  shared_preferences: ^2.3.3
  dio: ^5.7.0
  flutter_pdfview: ^1.3.4
  path_provider: ^2.1.5
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  fonts: 
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-SemiBold.ttf
    - family: SFproDisplay
      fonts:
        - asset: assets/fonts/SFPRODISPLAYBOLD.ttf
        - asset: assets/fonts/SFPRODISPLAYREGULAR.ttf
  assets:
    - assets/
    - assets/images/
    
        
