// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDh1uSarDrq2K_lkmz59jlgvMyowu59O0g',
    appId: '1:244170931963:web:2b194876de2d08bd693a5e',
    messagingSenderId: '244170931963',
    projectId: 'hustlehub-efee2',
    authDomain: 'hustlehub-efee2.firebaseapp.com',
    storageBucket: 'hustlehub-efee2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJIvRMD1Zyq48yeTlLChbW8NVA-sHej9U',
    appId: '1:244170931963:android:4b48e7b12fe9f96f693a5e',
    messagingSenderId: '244170931963',
    projectId: 'hustlehub-efee2',
    storageBucket: 'hustlehub-efee2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChOG1QdmbRpgNczGmqETNcIe-YuUSwNAc',
    appId: '1:244170931963:ios:3c578cb813f31d2f693a5e',
    messagingSenderId: '244170931963',
    projectId: 'hustlehub-efee2',
    storageBucket: 'hustlehub-efee2.appspot.com',
    iosBundleId: 'com.example.hastlehub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChOG1QdmbRpgNczGmqETNcIe-YuUSwNAc',
    appId: '1:244170931963:ios:3c578cb813f31d2f693a5e',
    messagingSenderId: '244170931963',
    projectId: 'hustlehub-efee2',
    storageBucket: 'hustlehub-efee2.appspot.com',
    iosBundleId: 'com.example.hastlehub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDh1uSarDrq2K_lkmz59jlgvMyowu59O0g',
    appId: '1:244170931963:web:94fe51af8f43c4cb693a5e',
    messagingSenderId: '244170931963',
    projectId: 'hustlehub-efee2',
    authDomain: 'hustlehub-efee2.firebaseapp.com',
    storageBucket: 'hustlehub-efee2.appspot.com',
  );
}
